# Generated by Django 6.0.5 on 2026-05-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
